version: '3.3'
services:
  stream:
    platform: linux/amd64
    # build:  ./services/stream/Dockerfile.test
    image:  streamingservice
    container_name: stream
    environment:
      # - DB=cassandra
      - BATCH_SIZE=1000
    ports:
    # for spark UI
      - 4040:4040
    volumes:
      - ./data:/data
      - ./services/stream:/stream
    command:
      spark-submit stream.py
